/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package javaapplication13;
import javax.swing.JOptionPane;
/**
 *
 * @author lenovo
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuFileExit = new javax.swing.JMenuItem();
        menuFileMaster = new javax.swing.JMenu();
        menuMasterBarang = new javax.swing.JMenuItem();
        menuMasterKonsumen = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuTransaksiInput = new javax.swing.JMenuItem();
        menuUtility = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();
        menuHelpAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Penjualan");

        menuFile.setMnemonic('F');
        menuFile.setText("File");

        menuFileExit.setMnemonic('X');
        menuFileExit.setText("Exit");
        menuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileExitActionPerformed(evt);
            }
        });
        menuFile.add(menuFileExit);

        menuFileMaster.setMnemonic('M');
        menuFileMaster.setText("Master");

        menuMasterBarang.setText("Barang");
        menuMasterBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterBarangActionPerformed(evt);
            }
        });
        menuFileMaster.add(menuMasterBarang);

        menuMasterKonsumen.setText("Konsumen");
        menuMasterKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterKonsumenActionPerformed(evt);
            }
        });
        menuFileMaster.add(menuMasterKonsumen);

        menuFile.add(menuFileMaster);

        jMenuBar1.add(menuFile);

        menuTransaksi.setText("Transaksi");

        menuTransaksiInput.setText("Input");
        menuTransaksiInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiInputActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuTransaksiInput);

        jMenuBar1.add(menuTransaksi);

        menuUtility.setText("Utility");
        jMenuBar1.add(menuUtility);

        menuHelp.setText("Help");

        menuHelpAbout.setText("About");
        menuHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuHelpAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Dibuat oleh Muhammad Ilham Nugraha");
    }//GEN-LAST:event_menuHelpAboutActionPerformed

    private void menuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileExitActionPerformed
        // TODO add your handling code here:
        //new FormUtama().setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_menuFileExitActionPerformed

    private void menuMasterBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterBarangActionPerformed
        // TODO add your handling code here:
        new FormBarang().setVisible(true);
        
    }//GEN-LAST:event_menuMasterBarangActionPerformed

    private void menuMasterKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterKonsumenActionPerformed
        // TODO add your handling code here:
        new FormKonsumen().setVisible(true);
    }//GEN-LAST:event_menuMasterKonsumenActionPerformed

    private void menuTransaksiInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiInputActionPerformed
        // TODO add your handling code here:
        new FormTransaksi().setVisible(true);
    }//GEN-LAST:event_menuTransaksiInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuFileExit;
    private javax.swing.JMenu menuFileMaster;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuHelpAbout;
    private javax.swing.JMenuItem menuMasterBarang;
    private javax.swing.JMenuItem menuMasterKonsumen;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenuItem menuTransaksiInput;
    private javax.swing.JMenu menuUtility;
    // End of variables declaration//GEN-END:variables
}
